-- Migration: Add follow_up_first_message to scheduled_follow_ups
-- Description: Stores the first message for the agent to say on the follow-up call (continuity from previous call).
-- Do not expose this column on the follow-ups dashboard API.
-- Date: 2025-02-01

ALTER TABLE scheduled_follow_ups
  ADD COLUMN IF NOT EXISTS follow_up_first_message TEXT;

COMMENT ON COLUMN scheduled_follow_ups.follow_up_first_message IS 'Optional first message for the agent on the follow-up call; generated by LLM when follow_up_required=true. Not shown on dashboard.';
